ViewComponents/AboutItemViewComponent.cs
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using CMS.DataEngine;
using Microsoft.AspNetCore.Mvc;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Routing;
using CMS.DocumentEngine.Types.NerdLab;
using CMS.MediaLibrary;
using Kentico.Content.Web.Mvc;
using nerds_lab.Models;

namespace nerds_lab.ViewComponents
{
    public class AboutItemViewComponent : ViewComponent
    {
        private readonly IPageRetriever pageRetriever;
        private readonly IMediaFileUrlRetriever  mediaFileUrlRetriever;

        public AboutItemViewComponent(IPageRetriever pageRetriever, IMediaFileUrlRetriever mediaFileUrlRetriever)
        {
            // Initializes instances of required services using dependency injection
            this.pageRetriever = pageRetriever;
            this.mediaFileUrlRetriever = mediaFileUrlRetriever;
        }
        
        private string _getMediaUrl(AboutItem aboutItem)
        {
            MediaFileInfo assetToMediaFileInfo =
                new ObjectQuery<MediaFileInfo>().ForAssets(aboutItem.Fields.Image).GetEnumerableTypedResult().First();
            return mediaFileUrlRetriever.Retrieve(assetToMediaFileInfo).RelativePath;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Gets all pages under the 'HomeItems' node in the content tree
            IEnumerable<AboutItem> aboutItems = await pageRetriever.RetrieveAsync<AboutItem>(
                query => query
                    .Path("/AboutPage", PathTypeEnum.Children)
                    .OrderByAscending("NodeOrder"),
                cache => cache
                    .Key($"{nameof(AboutItemViewComponent)}|{nameof(InvokeAsync)}|AboutPage")
                    // Flushes the cache when a new navigation item is created or the page order changes
                    .Dependencies(
                        (pages, builder) => builder.PagePath("/AboutPage", PathTypeEnum.Children).PageOrder())
                    .Expiration(System.TimeSpan.FromDays(1), useSliding: true));


            IEnumerable<AboutItemViewModel> aboutItemViewModel = aboutItems.Select(aboutItem =>
                new AboutItemViewModel
                {
                    Name = aboutItem.Name,
                    Designation = aboutItem.Designation,
                    Image = _getMediaUrl(aboutItem),
                    Quote = aboutItem.Quote,
                });

            return View(aboutItemViewModel);
        }
    }
}

ViewComponents/CareerItemViewComponent.cs
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Routing;
using CMS.DocumentEngine.Types.NerdLab;
using Kentico.Content.Web.Mvc;
using nerds_lab.Models;

namespace nerds_lab.ViewComponents
{
    public class CareerItemViewComponent : ViewComponent
    {
        private readonly IPageRetriever pageRetriever;
        private readonly IPageUrlRetriever pageUrlRetriever;

        public CareerItemViewComponent(IPageRetriever pageRetriever, IPageUrlRetriever pageUrlRetriever)
        {
            // Initializes instances of required services using dependency injection
            this.pageRetriever = pageRetriever;
            this.pageUrlRetriever = pageUrlRetriever;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Gets all pages under the 'HomeItems' node in the content tree
            IEnumerable<CareerItem> careerItem = await pageRetriever.RetrieveAsync<CareerItem>(
                query => query
                    .Path("/CareerPage", PathTypeEnum.Children)
                    .OrderByAscending("NodeOrder"),
                cache => cache
                    .Key($"{nameof(CareerItemViewComponent)}|{nameof(InvokeAsync)}|CareerPage")
                    // Flushes the cache when a new navigation item is created or the page order changes
                    .Dependencies(
                        (pages, builder) => builder.PagePath("/CareerPage", PathTypeEnum.Children).PageOrder())
                    .Expiration(System.TimeSpan.FromDays(1), useSliding: true));


            IEnumerable<CareerItemViewModel> careerItemViewModel = careerItem.Select(careerItem =>
                new CareerItemViewModel
                {
                    CareerItemTitle = careerItem.Title,
                    CareerItemDescription = careerItem.Description,
                    CareerItemRibbonColor = careerItem.RibbonColor,
                    CareerItemResponsibility = careerItem.Responsibility,
                    CareerItemTechStack = careerItem.TechStack,
                    CareerItemProject = careerItem.Project,
                    CareerItemExperience = careerItem.Experience,
                    CareerItemLocation = careerItem.Location,
                    CareerItemCompensation = careerItem.Compensation,
                    CareerItemApplyText = careerItem.ApplyText,
                });

            return View(careerItemViewModel);
        }
    }
}

ViewComponents/HomeItemViewComponent.cs
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;

using Microsoft.AspNetCore.Mvc;

using CMS.DocumentEngine;
using CMS.DocumentEngine.Routing;
using CMS.DocumentEngine.Types.NerdLab;

using Kentico.Content.Web.Mvc;

using nerds_lab.Models;

namespace nerds_lab.ViewComponents
{
    public class HomeItemViewComponent : ViewComponent
    {
        private readonly IPageRetriever pageRetriever;
        private readonly IPageUrlRetriever pageUrlRetriever;

        public HomeItemViewComponent(IPageRetriever pageRetriever, IPageUrlRetriever pageUrlRetriever)
        {
            // Initializes instances of required services using dependency injection
            this.pageRetriever = pageRetriever;
            this.pageUrlRetriever = pageUrlRetriever;
        }

        private string _getRelativePath(HomeItem homeItem)
        {
            // Retrieves the node GUIDs of the selected pages from the 'Pages' property
            List<Guid> selectedPageGuids = homeItem?.Fields.LinkTo
                .Select(i => i.NodeGuid)
                .ToList();

            // Retrieves the pages that correspond to the selected GUIDs
            List<TreeNode> pages = pageRetriever.Retrieve<TreeNode>(query => query
                    .WhereIn("NodeGUID", selectedPageGuids))
                .ToList();

            return pageUrlRetriever.Retrieve(pages.First()).RelativePath;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Gets all pages under the 'HomeItems' node in the content tree
            IEnumerable<HomeItem> homeItems = await pageRetriever.RetrieveAsync<HomeItem>(
                    query => query
                         .Path("/HomeItems", PathTypeEnum.Children)
                         .OrderByAscending("NodeOrder"),
                    cache => cache
                         .Key($"{nameof(HomeItemViewComponent)}|{nameof(InvokeAsync)}|HomeItems")
                         // Flushes the cache when a new navigation item is created or the page order changes
                         .Dependencies((pages, builder) => builder.PagePath("/HomeItems", PathTypeEnum.Children).PageOrder())
                         .Expiration(System.TimeSpan.FromDays(1), useSliding: true));
            
            
            IEnumerable<HomeItemViewModel> homeItemViewModels = homeItems.Select(homeItem => new HomeItemViewModel
            {
                HomeItemTitle = homeItem.Title,
                HomeItemDescription = homeItem.Description,
                HomeItemProgressText = homeItem.ProgressText,
                HomeItemProgressColor = homeItem.ProgressColor,
                HomeItemProgressPercentage = homeItem.ProgressPercentage,
                HomeItemPageLink = _getRelativePath(homeItem)
            });
            
            return View(homeItemViewModels);
        }
    }
}

Views/Shared/PageTypes/NerdLab_AboutPage.cshtml
@addTagHelper *, Kentico.Content.Web.Mvc

@model Kentico.Content.Web.Mvc.Routing.IPageViewModel<CMS.DocumentEngine.Types.NerdLab.AboutPage>

@{
    ViewBag.Title = Model.Page.DocumentName;
}

@section styles
{
    @* Includes CSS necessary for page builder functionality *@
    <page-builder-styles/>
    <link rel="stylesheet" href="~/css/about_us.css">
}

@section scripts
{
    @* Includes scripts necessary for page builder functionality *@
    <page-builder-scripts/>
}

<div class="about-us-content-container">
    @Html.Raw(Model.Page.Fields.AboutUsContent)
    @await Component.InvokeAsync("AboutItem")
</div>

Views/Shared/PageTypes/NerdLab_CareerPage.cshtml
@addTagHelper *, Kentico.Content.Web.Mvc

@model Kentico.Content.Web.Mvc.Routing.IPageViewModel<CMS.DocumentEngine.Types.NerdLab.CareerPage>

@{
    ViewBag.Title = Model.Page.DocumentName;
}

@section styles
{
    @* Includes CSS necessary for page builder functionality *@
    <page-builder-styles/>
    <link rel="stylesheet" href="~/css/career.css">
}

@section scripts
{
    @* Includes scripts necessary for page builder functionality *@
    <page-builder-scripts/>
}

<div class="career-container">
    @Html.Raw(Model.Page.Fields.CareerContent)
    <editable-area area-identifier="editableArea"/>
    
    @await Component.InvokeAsync("CareerItem")
</div>

Views/Shared/PageTypes/NerdLab_ContactUsPage.cshtml
@addTagHelper *, Kentico.Content.Web.Mvc

@model Kentico.Content.Web.Mvc.Routing.IPageViewModel<CMS.DocumentEngine.Types.NerdLab.ContactUsPage>

@{
    ViewBag.Title = Model.Page.DocumentName;
}

@section styles
{
    @* Includes CSS necessary for page builder functionality *@
    <page-builder-styles/>
    <link rel="stylesheet" href="~/css/contact_us.css">
}

@section scripts
{
    @* Includes scripts necessary for page builder functionality *@
    <page-builder-scripts/>
}

<div class="contact-container">
    @Html.Raw(Model.Page.Fields.ContactUsContent)
    <editable-area area-identifier="editableArea"/>
</div>

Views/Shared/PageTypes/NerdLab_Home.cshtml
@addTagHelper *, Kentico.Content.Web.Mvc

@using CMS.DataEngine
@using CMS.DocumentEngine
@using CMS.DocumentEngine.Types.NerdLab
@using CMS.MediaLibrary
@using Kentico.Content.Web.Mvc
@model Kentico.Content.Web.Mvc.Routing.IPageViewModel<CMS.DocumentEngine.Types.NerdLab.Home>

@{
    ViewBag.Title = Model.Page.DocumentName;
}

@section styles
{
    @* Includes CSS necessary for page builder functionality *@
    <page-builder-styles/>
    <link rel="stylesheet" href="~/css/home_item.css">
}

@section scripts
{
    @* Includes scripts necessary for page builder functionality *@
    <page-builder-scripts/>
}

@{
    // This is C# code
    MediaFileInfo assetToMediaFileInfo =
        new ObjectQuery<MediaFileInfo>().ForAssets(@Model.Page.Fields.Icon).GetEnumerableTypedResult().First();
    string nerdsLabIconUrl = MediaLibraryHelper.GetDirectUrl(assetToMediaFileInfo);
}

@{
    FeatureItem featureItem = (FeatureItem)@Model.Page.Fields.FeatureItem.First();
}


<div class="intro-container">
    <div class="intro-left-section">
        <h2>@Model.Page.Fields.Title</h2>
        <p>@Model.Page.Fields.Description</p>

    </div>
    <div class="intro-right-section">
        <img class="intro-image" src="@nerdsLabIconUrl" alt="Nerds Lab Icon">
    </div>
    <editable-area area-identifier="editableArea"/>
</div>

<!--  Feature Home Item-->
<a class="no-underline" href="~/products" title="~/products">
<div class="feature-home-item">
    <div class="feature-item-left-section">
        <button class="image-button">
            <img src="~/assets/play_icon.png" alt="Play Image">
        </button>
    </div>
    <div class="feature-item-right-section">
        <h2>@featureItem.Fields.Title</h2>
        <p>
            @featureItem.Fields.Description
        </p>
    </div>
</div>
</a>

@await Component.InvokeAsync("HomeItem")

Views/Shared/PageTypes/NerdLab_PrivacyPage.cshtml
@addTagHelper *, Kentico.Content.Web.Mvc

@model Kentico.Content.Web.Mvc.Routing.IPageViewModel<CMS.DocumentEngine.Types.NerdLab.PrivacyPage>

@{
    ViewBag.Title = Model.Page.DocumentName;
}

@section styles
{
    @* Includes CSS necessary for page builder functionality *@
    <page-builder-styles/>
    <link rel="stylesheet" href="~/css/privacy.css">
}

@section scripts
{
    @* Includes scripts necessary for page builder functionality *@
    <page-builder-scripts/>
}

<div class="privacy-container">
    @Html.Raw(Model.Page.Fields.PrivacyContent)
</div>

Views/Shared/PageTypes/NerdLab_Product.cshtml
@addTagHelper *, Kentico.Content.Web.Mvc

@model Kentico.Content.Web.Mvc.Routing.IPageViewModel<CMS.DocumentEngine.Types.NerdLab.Product>

@{
    ViewBag.Title = Model.Page.DocumentName;
}

@section styles
{
    @* Includes CSS necessary for page builder functionality *@
    <page-builder-styles/>
     <link rel="stylesheet" href="~/css/product.css">
}

@section scripts
{
    @* Includes scripts necessary for page builder functionality *@
    <page-builder-scripts/>
}

@{
    var color = "#F7E290";
    if (@Model.Page.Fields.StatusProgressColor == 0)
    {
        color = "#F7E290";
    }
    else if (@Model.Page.Fields.StatusProgressColor == 1)
    {
        color = "#a7acec";
    }
    else
    {
        color = "#EA9595";
    }
}

<div class="product-container">
    <div class="video-container">
        <iframe src="@Model.Page.Fields.VideoLink" ></iframe>
    </div>
    <h2>@Model.Page.Fields.Title</h2>
    @Html.Raw(Model.Page.Fields.Description)

    <div class="image-container">
        <img src="@Model.Page.Fields.ImageLink" alt="Your Image Description">
    </div>

    <h2>@Model.Page.Fields.UsecaseTitle</h2>
    @Html.Raw(Model.Page.Fields.UsecaseDescription)

    <h2>@Model.Page.Fields.PricingTitle</h2>
    @Html.Raw(Model.Page.Fields.PricingDescription)

    @* <h2>Partners</h2> *@
    @* <div class="partner-container"> *@
    @*     <div class="partner-items"> *@
    @*         <div class="partners">Item 1</div> *@
    @*         <div class="partners">Item 2</div> *@
    @*         <div class="partners">Item 3</div> *@
    @*         <div class="partners">Item 4</div> *@
    @*     </div> *@
    @* </div> *@

    <h2>@Model.Page.Fields.StatusTitle</h2>
    @Html.Raw(Model.Page.Fields.StatusDescription)
    <div class="progress-bar">
        <div class="progress-level" style="--progress: @Model.Page.Fields.StatusProgressPercentage.ToString()%; --color: @color;"></div>
    </div>
</div>

Views/Shared/PageTypes/NerdLab_ProductSection.cshtml
@addTagHelper *, Kentico.Content.Web.Mvc

@model Kentico.Content.Web.Mvc.Routing.IPageViewModel<CMS.DocumentEngine.Types.NerdLab.ProductSection>

@{
    ViewBag.Title = Model.Page.DocumentName;
}

@section styles
{
    @* Includes CSS necessary for page builder functionality *@
    <page-builder-styles/>
    <link rel="stylesheet" href="~/css/home_item.css">
}

@section scripts
{
    @* Includes scripts necessary for page builder functionality *@
    <page-builder-scripts/>
}

<div class="product-container">
    @await Component.InvokeAsync("HomeItem")
</div>